apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: petclinic
type: Opaque
data:
  secret: TWpsbU1HWTBOemRtTm1FMk9EUmxaakE0TlRCa05EaGlPV1pqTlRFellqbGpZVFl4TkdKa1lqTXpPVGszTlRnellqTm1ORFUxTkRCaE0ySTBOVE5tWVRrMk1EVmlObVV4WkdRNE1EZzJORGxqT0dVeVpEZzNOakkwTVRWaE5tUmhZbVpoT1E9PQ==
