{{- if and .Values.ingress.enabled (eq .Values.global.platform "openshift") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: petclinic-angular
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: petclinic-angular
    {{- include "petclinic.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.host }}
  host: {{ .Values.ingress.host }}
  {{- end }}
  to:
    kind: Service
    name: petclinic-angular
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
