apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oss-tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: {{ .Values.charts.tempo.repoURL | quote }}
      chart: tempo
      targetRevision: {{ .Values.charts.tempo.version | quote }}
      helm:
        valueFiles:
          - $values/observability/grafana/values-oss-tempo.yaml
    - repoURL: {{ .Values.repoURL | quote }}
      targetRevision: {{ .Values.targetRevision | quote }}
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace.observability | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
