apiVersion: gateway.networking.k8s.io/v1alpha2
kind: BackendTLSPolicy
metadata:
  name: secure-jenkins-backend
  namespace: jenkins
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: jenkins
  validation:
    # Use CA certificate defined in ConfigMap for TLS verification
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: internal-ca-cert
    hostname: jenkins.jenkins.svc.cluster.local
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: BackendTLSPolicy
metadata:
  name: secure-headlamp-backend
  namespace: headlamp
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: headlamp
  validation:
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: internal-ca-cert
    hostname: headlamp.headlamp.svc.cluster.local
