commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: petclinic

resources:
  - namespace.yml
  # Individual apps
  - gateway-k8s/gateway-deployment.yml
  - gateway-k8s/gateway-service.yml
  - gateway-k8s/gateway-postgresql.yml
  - gateway-k8s/jwt-secret.yml
  - customers-k8s/customers-deployment.yml
  - customers-k8s/customers-service.yml
  - customers-k8s/customers-postgresql.yml
  - customers-k8s/jwt-secret.yml
  - billing-k8s/billing-deployment.yml
  - billing-k8s/billing-service.yml
  - billing-k8s/billing-postgresql.yml
  - billing-k8s/jwt-secret.yml
# service discovery eureka/consul

patchesJson6902:
