#!/usr/bin/env bash
# Installs Jenkins (jenkinsci/helm-charts) with the platform overlay for
# ${J2026_PLATFORM}, the JCasC fragments under jenkins/casc/, and a generated
# values overlay that wires controller.containerEnv to this repo's
# config/config.yaml + the "${J2026_JENKINS_CREDENTIALS_SECRET}" Secret
# (created by 01-namespaces.sh). On OpenShift, also applies the Route.
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
source "$(dirname "${BASH_SOURCE[0]}")/lib/config.sh"

GENERATED_DIR="${J2026_ROOT_DIR}/.generated"
mkdir -p "${GENERATED_DIR}"
RUNTIME_VALUES="${GENERATED_DIR}/jenkins-runtime-values.yaml"

log_step "Generating runtime values overlay (${RUNTIME_VALUES#${J2026_ROOT_DIR}/})"
cat >"${RUNTIME_VALUES}" <<EOF
# Generated by scripts/04-jenkins.sh from config/config.yaml - do not edit by
# hand, do not commit (see .gitignore). Fully replaces
# controller.containerEnv from helm/jenkins/values-common.yaml with values
# resolved from this repo's config.
controller:
  containerEnv:
    - name: JENKINS_ADMIN_ID
      value: "${J2026_JENKINS_ADMIN_USER}"
    - name: JENKINS_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: admin-password
    - name: JENKINS_PLATFORM_ENGINEER_ID
      value: "${J2026_PLATFORM_ENGINEER_USER}"
    - name: JENKINS_PLATFORM_ENGINEER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: platform-engineer-password
    - name: JENKINS_URL
      value: "http://localhost:8080/"
    - name: JENKINS2026_REPO_URL
      value: "${J2026_SELF_REPO_URL}"
    - name: JENKINS2026_REPO_BRANCH
      value: "${J2026_SELF_REPO_BRANCH}"
    - name: JENKINS2026_DEV_REPO_BRANCH
      value: "${J2026_SELF_REPO_DEV_BRANCH}"
    - name: JENKINS2026_PLATFORM
      value: "${J2026_PLATFORM}"
    - name: PETCLINIC_REGISTRY
      value: "${J2026_PETCLINIC_REGISTRY}"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://otel-collector-gateway.${J2026_OBS_NAMESPACE}.svc.cluster.local:4317"
    - name: OTEL_LOGS_BACKEND_URL
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: otel-logs-backend-url
          optional: true
    - name: GRAFANA_BASE_URL
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: grafana-base-url
          optional: true
    - name: GRAFANA_TRACES_DASHBOARD_UID
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: grafana-traces-dashboard-uid
          optional: true
    - name: REGISTRY_USERNAME
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: registry-username
          optional: true
    - name: REGISTRY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: registry-password
          optional: true
    - name: GIT_USERNAME
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: git-username
          optional: true
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: git-token
          optional: true
EOF

helm_args=(
  upgrade --install "${J2026_JENKINS_RELEASE}" "${J2026_JENKINS_CHART_NAME}"
  --namespace "${J2026_JENKINS_NAMESPACE}"
  --create-namespace
  -f "${J2026_ROOT_DIR}/helm/jenkins/values-common.yaml"
  -f "${J2026_ROOT_DIR}/helm/jenkins/values-${J2026_PLATFORM}.yaml"
  -f "${RUNTIME_VALUES}"
  --set-file "controller.JCasC.configScripts.base=${J2026_ROOT_DIR}/jenkins/casc/jcasc-base.yaml"
  --set-file "controller.JCasC.configScripts.otel=${J2026_ROOT_DIR}/jenkins/casc/jcasc-otel.yaml"
  --set-file "controller.JCasC.configScripts.seed-job=${J2026_ROOT_DIR}/jenkins/casc/jcasc-seed-job.yaml"
  --wait --timeout 10m --debug
)

if [[ -n "${J2026_JENKINS_CHART_VERSION}" ]]; then
  helm_args+=(--version "${J2026_JENKINS_CHART_VERSION}")
fi

log_step "Installing ${J2026_JENKINS_RELEASE} (${J2026_JENKINS_CHART_NAME}) into ${J2026_JENKINS_NAMESPACE} [platform=${J2026_PLATFORM}]"
helm "${helm_args[@]}"

if [[ "${J2026_PLATFORM}" == "openshift" ]]; then
  log_step "Applying OpenShift Route for Jenkins"
  yq eval ".metadata.namespace = \"${J2026_JENKINS_NAMESPACE}\"" \
    "${J2026_ROOT_DIR}/helm/jenkins/openshift/route.yaml" | kubectl apply -f -
fi

log_info "Jenkins ready. Forward the UI with:"
log_info "  kubectl -n ${J2026_JENKINS_NAMESPACE} port-forward svc/${J2026_JENKINS_RELEASE} 8080:8080"
