#!/usr/bin/env bash
# Installs Jenkins (jenkinsci/helm-charts) with the platform overlay for
# ${J2026_PLATFORM}, the JCasC fragments under jenkins/casc/, and a generated
# values overlay that wires controller.containerEnv to this repo's
# config/config.yaml + the "${J2026_JENKINS_CREDENTIALS_SECRET}" Secret
# (created by 01-namespaces.sh). On OpenShift, also applies the Route.
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
source "$(dirname "${BASH_SOURCE[0]}")/lib/config.sh"

log_step "Pre-installation cleanup of JCasC ConfigMaps"
# Delete any old JCasC ConfigMaps to prevent merge conflicts with new files.
# Using '|| true' to ignore errors if they don't exist.
kubectl delete configmap -n "${J2026_JENKINS_NAMESPACE}" \
  -l "app.kubernetes.io/instance=${J2026_JENKINS_RELEASE},jenkins-jenkins-config=true" --ignore-not-found=true || true

GENERATED_DIR="${J2026_ROOT_DIR}/.generated"
mkdir -p "${GENERATED_DIR}"
RUNTIME_VALUES="${GENERATED_DIR}/jenkins-runtime-values.yaml"

log_step "Generating runtime values overlay (${RUNTIME_VALUES#${J2026_ROOT_DIR}/})"

grafana_base_url=""
if [[ "${J2026_OBS_MODE}" == "grafana-cloud" ]]; then
  if kubectl get secret "${J2026_GRAFANA_CLOUD_SECRET}" -n "${J2026_OBS_NAMESPACE}" >/dev/null 2>&1; then
    grafana_base_url="$(kubectl get secret "${J2026_GRAFANA_CLOUD_SECRET}" -n "${J2026_OBS_NAMESPACE}" -o jsonpath='{.data.GRAFANA_BASE_URL}' | base64 -d || true)"
  fi
elif [[ "${J2026_OBS_MODE}" == "oss" ]]; then
  grafana_base_url="http://localhost:3000"
fi

if [[ -n "${grafana_base_url}" ]]; then
  kubectl patch secret "${J2026_JENKINS_CREDENTIALS_SECRET}" -n "${J2026_JENKINS_NAMESPACE}" \
    --type=merge -p "{\"stringData\":{\"grafana-base-url\":\"${grafana_base_url}\"}}"
fi

cat >"${RUNTIME_VALUES}" <<EOF
# Generated by scripts/04-jenkins.sh from config/config.yaml - do not edit by
# hand, do not commit (see .gitignore). Fully replaces
# controller.containerEnv from helm/jenkins/values-common.yaml with values
# resolved from this repo's config.
controller:
  jenkinsUrl: "${J2026_JENKINS_URL}"
  containerEnv:
    - name: JENKINS_ADMIN_ID
      value: "${J2026_JENKINS_ADMIN_USER}"
    - name: JENKINS_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: admin-password
    - name: JENKINS_URL
      value: "http://localhost:8080/"
    - name: JENKINS2026_REPO_URL
      value: "${J2026_SELF_REPO_URL}"
    - name: JENKINS2026_GITOPS_REPO_URL
      value: "https://github.com/nubenetes/jenkins-2026-gitops-config.git"
    - name: JENKINS2026_REPO_BRANCH
      value: "${J2026_SELF_REPO_BRANCH}"
    - name: JENKINS2026_PLATFORM
      value: "${J2026_PLATFORM}"
    - name: JENKINS2026_GENAI_SERVICE_ENABLED
      value: "${J2026_MICROSERVICES_GENAI_SERVICE_ENABLED}"
    - name: MICROSERVICES_REGISTRY
      value: "${J2026_MICROSERVICES_REGISTRY}"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://otel-collector-gateway.${J2026_OBS_NAMESPACE}.svc.cluster.local:4317"
    - name: OTEL_LOGS_BACKEND_URL
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: otel-logs-backend-url
          optional: true
    - name: GRAFANA_BASE_URL
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: grafana-base-url
          optional: true
    - name: GRAFANA_TRACES_DASHBOARD_UID
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: grafana-traces-dashboard-uid
          optional: true
    - name: MICROSERVICES_URL
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: microservices-url
          optional: true
    - name: MICROSERVICES_DEVELOP_URL
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: microservices-develop-url
          optional: true
    - name: REGISTRY_USERNAME
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: registry-username
          optional: true
    - name: REGISTRY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: registry-password
          optional: true
    - name: GIT_USERNAME
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: git-username
          optional: true
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: git-token
          optional: true
    - name: JENKINS_OIDC_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: oidc-client-id
          optional: true
    - name: JENKINS_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: oidc-client-secret
          optional: true
    - name: JENKINS_OIDC_ADMIN_EMAIL
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: oidc-admin-email
          optional: true
    - name: ARGOCD_SERVER
      value: "argocd-server.${J2026_ARGOCD_NAMESPACE}.svc.cluster.local"
    - name: ARGOCD_AUTH_TOKEN
      valueFrom:
        secretKeyRef:
          name: ${J2026_JENKINS_CREDENTIALS_SECRET}
          key: argocd-token
          optional: true
EOF

helm_args=(
  upgrade --install "${J2026_JENKINS_RELEASE}" "${J2026_JENKINS_CHART_NAME}"
  --namespace "${J2026_JENKINS_NAMESPACE}"
  --create-namespace
  -f "${J2026_ROOT_DIR}/helm/jenkins/values-common.yaml"
  -f "${J2026_ROOT_DIR}/helm/jenkins/values-${J2026_PLATFORM}.yaml"
  -f "${RUNTIME_VALUES}"
  --set-file "controller.JCasC.configScripts.base=${J2026_ROOT_DIR}/jenkins/casc/jcasc-base.yaml"
  --set-file "controller.JCasC.configScripts.otel=${J2026_ROOT_DIR}/jenkins/casc/jcasc-otel.yaml"
  --set-file "controller.JCasC.configScripts.seed-job=${J2026_ROOT_DIR}/jenkins/casc/jcasc-seed-job.yaml"
)

if [[ -n "${J2026_JENKINS_CHART_VERSION}" ]]; then
  helm_args+=(--version "${J2026_JENKINS_CHART_VERSION}")
fi

log_step "Installing ${J2026_JENKINS_RELEASE} (${J2026_JENKINS_CHART_NAME}) into ${J2026_JENKINS_NAMESPACE} [platform=${J2026_PLATFORM}]"
helm "${helm_args[@]}"

# Use wait_for_resource with a 15m timeout. If it fails, trigger a manual
# rollback to keep the cluster clean.
if ! wait_for_resource "statefulset" "${J2026_JENKINS_RELEASE}" "${J2026_JENKINS_NAMESPACE}" "15m"; then
  log_error "Jenkins rollout failed, rolling back..."
  helm rollback "${J2026_JENKINS_RELEASE}" -n "${J2026_JENKINS_NAMESPACE}"
  exit 1
fi

if [[ "${J2026_PLATFORM}" == "openshift" ]]; then
  log_step "Applying OpenShift Route for Jenkins"
  yq eval ".metadata.namespace = \"${J2026_JENKINS_NAMESPACE}\"" \
    "${J2026_ROOT_DIR}/helm/jenkins/openshift/route.yaml" | kubectl apply -f -
fi

log_info "Jenkins ready. Forward the UI with:"
log_info "  kubectl -n ${J2026_JENKINS_NAMESPACE} port-forward svc/${J2026_JENKINS_RELEASE} 8080:8080"
