#!/usr/bin/env bash
# Applies the Tekton pipeline-as-code (Tasks, Pipelines, Triggers, RBAC from
# tekton/) and generates one PipelineRun per service per environment from
# jenkins/pipelines/seed/services.yaml. This is the Tekton analogue of the
# Jenkins seed job (jenkins/pipelines/seed/seed_jobs.groovy + 06-seed-pipelines.sh):
#   - applying the Tasks/Pipelines/Triggers == the seed creating the jobs
#   - the per-service PipelineRuns == the generated '<svc>' pipeline jobs
# The initial PipelineRuns are kicked asynchronously (like the per-service Jenkins
# builds, which run after the seed job): up.sh does not block on the long
# build/deploy. Idempotent: manifests are kubectl-applied; runs use generateName.
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
source "$(dirname "${BASH_SOURCE[0]}")/lib/config.sh"

if [[ "${J2026_CI_ENGINE}" != "tekton" ]]; then
  log_info "ci.engine='${J2026_CI_ENGINE}' (not tekton) - skipping Tekton pipelines."
  exit 0
fi

PIPELINE_NS="${J2026_TEKTON_PIPELINE_NAMESPACE}"
SERVICES_YAML="${J2026_ROOT_DIR}/jenkins/pipelines/seed/services.yaml"
GEN_DIR="${J2026_ROOT_DIR}/.generated/tekton"
mkdir -p "${GEN_DIR}"

# The Tasks/Pipelines/Triggers/RBAC under tekton/ are GitOps-managed by the
# tekton-pipeline-as-code ArgoCD Application (applied by 04-tekton.sh via the
# tekton app-of-apps). Wait for ArgoCD to have synced the Pipeline + the
# pipeline ServiceAccount before kicking PipelineRuns against them.
log_step "Waiting for ArgoCD to sync the Tekton pipelines-as-code into ${PIPELINE_NS}"
timeout 600 bash -c '
  until kubectl -n "'"${PIPELINE_NS}"'" get pipeline microservices-pipeline >/dev/null 2>&1 \
     && kubectl -n "'"${PIPELINE_NS}"'" get serviceaccount tekton-ci >/dev/null 2>&1; do
    sleep 10
  done
' || { log_error "microservices-pipeline / tekton-ci SA not present within 10m - check 'kubectl -n ${J2026_ARGOCD_NAMESPACE} get application tekton-pipeline-as-code'"; exit 1; }

# --- per-service PipelineRun generation (seed equivalent) --------------------
# Environments: 'stable' always; 'develop' only when the develop track is enabled
# (mirrors seed_jobs.groovy gating on JENKINS2026_DEVELOP_TRACK_ENABLED).
envs=(stable)
if [[ "${J2026_MICROSERVICES_DEVELOP_TRACK_ENABLED}" == "true" ]]; then
  envs+=(develop)
fi

otlp_endpoint="http://otel-collector-gateway.${J2026_OBS_NAMESPACE}.svc.cluster.local:4317"
svc_count="$(yq eval '.services | length' "${SERVICES_YAML}")"

log_step "Generating PipelineRuns for ${svc_count} service(s): ${J2026_MICROSERVICES_SERVICES}"
created=0
for i in $(seq 0 $((svc_count - 1))); do
  name="$(yq eval ".services[${i}].name" "${SERVICES_YAML}")"
  type="$(yq eval ".services[${i}].type // \"java\"" "${SERVICES_YAML}")"
  repo="$(yq eval ".services[${i}].repoUrl" "${SERVICES_YAML}")"
  module="$(yq eval ".services[${i}].module // \"\"" "${SERVICES_YAML}")"
  port="$(yq eval ".services[${i}].port" "${SERVICES_YAML}")"
  health="$(yq eval ".services[${i}].healthPath" "${SERVICES_YAML}")"

  for env in "${envs[@]}"; do
    if [[ "${env}" == "stable" ]]; then
      ns="${J2026_MICROSERVICES_NS_STABLE}"; src_branch="${J2026_MICROSERVICES_BRANCH_STABLE}"
    else
      ns="${J2026_MICROSERVICES_DEVELOP_NAMESPACE}"; src_branch="main"
    fi

    run_file="${GEN_DIR}/pipelinerun-${name}-${env}.yaml"
    cat >"${run_file}" <<EOT
# Generated by scripts/06-tekton-pipelines.sh - do not edit/commit.
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ${name}-${env}-
  namespace: ${PIPELINE_NS}
  labels:
    jenkins2026.io/service: "${name}"
    jenkins2026.io/env: "${env}"
spec:
  taskRunTemplate:
    serviceAccountName: tekton-ci
  pipelineRef:
    name: microservices-pipeline
  params:
    - name: service-name
      value: "${name}"
    - name: service-type
      value: "${type}"
    - name: git-repo-url
      value: "${repo}"
    - name: git-branch
      value: "${src_branch}"
    - name: module-path
      value: "${module}"
    - name: target-namespace
      value: "${ns}"
    - name: env-name
      value: "${env}"
    - name: port
      value: "${port}"
    - name: health-path
      value: "${health}"
    - name: image
      value: "${J2026_MICROSERVICES_REGISTRY}/${name}:${src_branch}"
    - name: registry-host
      value: "${J2026_MICROSERVICES_REGISTRY%%/*}"
    - name: self-repo-url
      value: "${J2026_SELF_REPO_URL}"
    - name: self-repo-branch
      value: "${J2026_SELF_REPO_BRANCH}"
    - name: otlp-endpoint
      value: "${otlp_endpoint}"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 4Gi
    # ghcr.io credentials (dockerconfigjson) read by Jib/Kaniko/Trivy via
    # DOCKER_CONFIG. Created by 01-namespaces.sh in the pipeline namespace.
    - name: dockerconfig
      secret:
        secretName: ${J2026_TEKTON_REGISTRY_SECRET}
        items:
          - key: .dockerconfigjson
            path: config.json
EOT

    if kubectl create -f "${run_file}" >/dev/null 2>&1; then
      log_info "  kicked PipelineRun for ${name} (${env})"
      ((created++)) || true
    else
      log_warn "  failed to create PipelineRun for ${name} (${env}) - see ${run_file#${J2026_ROOT_DIR}/}"
    fi
  done
done

log_info "Tekton pipelines applied; ${created} PipelineRun(s) kicked (running asynchronously)."
log_info "  Track them in the Tekton Dashboard or with: kubectl get pipelinerun -n ${PIPELINE_NS}"
