#!/usr/bin/env bash
# Exposes Jenkins, PetClinic and Headlamp on the public internet via the GKE
# Gateway API: one global external HTTPS Gateway (gke-l7-global-external-managed,
# using the static IP + managed certificate from terraform/gateway-bootstrap),
# one HTTPRoute per app, and a GCPBackendPolicy enabling Identity-Aware Proxy
# (IAP) in front of the Jenkins and Headlamp Services only - PetClinic stays
# public. See README.md "Public access (GKE Gateway API + IAP)".
#
# No-op if gateway.baseDomain / JENKINS2026_BASE_DOMAIN is empty (e.g. before
# terraform/gateway-bootstrap has been run once).
#
# NEEDS LIVE-CLUSTER VERIFICATION (next gke-provision run): the exact
# Gateway/HTTPRoute/GCPBackendPolicy field syntax below - in particular the
# `addresses[].type: NamedAddress` static-IP reference, the
# `networking.gke.io/certmap` annotation, cross-namespace HTTPRoute
# attachment via `allowedRoutes.namespaces.from: All`, and the
# GCPBackendPolicy `oauth2ClientSecret` field/key names - against the GKE
# Gateway API CRD versions actually installed on the cluster.
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
source "$(dirname "${BASH_SOURCE[0]}")/lib/config.sh"

if [[ -z "${J2026_GATEWAY_BASE_DOMAIN}" ]]; then
  log_info "gateway.baseDomain / JENKINS2026_BASE_DOMAIN is empty - gateway disabled, skipping."
  log_info "(set it, after running the gateway-bootstrap workflow once, to enable public access)"
  exit 0
fi

if [[ "${J2026_PLATFORM}" != "gke" ]]; then
  log_info "platform.target='${J2026_PLATFORM}' - the gke-l7-global-external-managed"
  log_info "GatewayClass and GCPBackendPolicy are GKE-specific, skipping."
  exit 0
fi

GENERATED_DIR="${J2026_ROOT_DIR}/.generated/gateway"
mkdir -p "${GENERATED_DIR}"

log_step "Generating Gateway (static IP '${J2026_GATEWAY_STATIC_IP_NAME}', certmap '${J2026_GATEWAY_CERTMAP_NAME}')"
cat >"${GENERATED_DIR}/gateway.yaml" <<EOF
# Generated by scripts/09-gateway.sh from config/config.yaml - do not edit by
# hand, do not commit (see .gitignore).
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${J2026_GATEWAY_NAME}
  namespace: ${J2026_JENKINS_NAMESPACE}
  annotations:
    networking.gke.io/certmap: ${J2026_GATEWAY_CERTMAP_NAME}
spec:
  gatewayClassName: gke-l7-global-external-managed
  addresses:
    - type: NamedAddress
      value: ${J2026_GATEWAY_STATIC_IP_NAME}
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        # The Gateway API CRD requires tls.certificateRefs or tls.options to
        # be non-empty when mode is Terminate. The actual certificate comes
        # from the networking.gke.io/certmap annotation above; this
        # pre-shared-certs option is GKE's documented placeholder to satisfy
        # that validation when using a certificate map.
        options:
          networking.gke.io/pre-shared-certs: ""
      allowedRoutes:
        namespaces:
          from: All
EOF

log_step "Generating HTTPRoutes (jenkins, petclinic, headlamp)"
cat >"${GENERATED_DIR}/httproute-jenkins.yaml" <<EOF
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_JENKINS}
  namespace: ${J2026_JENKINS_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_JENKINS_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_JENKINS_HOST}"
  rules:
    - backendRefs:
        - name: ${J2026_JENKINS_RELEASE}
          port: 8080
EOF

cat >"${GENERATED_DIR}/httproute-petclinic.yaml" <<EOF
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_PETCLINIC}
  namespace: ${J2026_PETCLINIC_NS_STABLE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_JENKINS_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_PETCLINIC_HOST}"
  rules:
    - backendRefs:
        - name: petclinic-angular
          port: 8080
EOF

cat >"${GENERATED_DIR}/httproute-headlamp.yaml" <<EOF
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_HEADLAMP}
  namespace: ${J2026_HEADLAMP_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_JENKINS_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_HEADLAMP_HOST}"
  rules:
    - backendRefs:
        - name: ${J2026_HEADLAMP_RELEASE}
          port: 80
EOF

log_step "Generating HealthCheckPolicy (jenkins)"
# The GCP load balancer's default health check requests "/", which Jenkins
# answers with 403 (anonymous read is disabled) instead of 200, so the
# backend never goes healthy ("no healthy upstream"). Point the health check
# at /login, which Jenkins always serves as 200.
cat >"${GENERATED_DIR}/healthcheckpolicy-jenkins.yaml" <<EOF
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ${J2026_JENKINS_RELEASE}
  namespace: ${J2026_JENKINS_NAMESPACE}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /login
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_JENKINS_RELEASE}
EOF

log_step "Generating GCPBackendPolicies (IAP for jenkins, headlamp)"
# GCPBackendPolicy requires the OAuth client ID as a literal
# spec.default.iap.clientID field, and its oauth2ClientSecret Secret to
# contain exactly one key ("client_secret") -
# ${J2026_GATEWAY_IAP_SECRET} (created by scripts/01-namespaces.sh) holds
# both client_id and client_secret for general use, so derive a
# single-key secret per namespace here.
declare -A iap_client_id
for ns in "${J2026_JENKINS_NAMESPACE}" "${J2026_HEADLAMP_NAMESPACE}"; do
  client_id="$(kubectl get secret "${J2026_GATEWAY_IAP_SECRET}" -n "${ns}" -o jsonpath='{.data.client_id}' 2>/dev/null | base64 -d || true)"
  client_secret="$(kubectl get secret "${J2026_GATEWAY_IAP_SECRET}" -n "${ns}" -o jsonpath='{.data.client_secret}' 2>/dev/null | base64 -d || true)"
  iap_client_id["${ns}"]="${client_id}"
  kubectl create secret generic "${J2026_GATEWAY_IAP_SECRET}-client-secret" -n "${ns}" \
    --from-literal=client_secret="${client_secret}" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null

  # IAP is enabled (fail-closed) on the Jenkins/Headlamp GCPBackendPolicies
  # below regardless of whether real OAuth credentials were configured in
  # scripts/01-namespaces.sh - an empty client_id means the public URLs
  # printed at the end of this script will error out until
  # IAP_OAUTH_CLIENT_ID/SECRET are set and up.sh is re-run.
  if [[ -z "${client_id}" ]]; then
    log_warn "IAP OAuth credentials are not configured in namespace '${ns}'"
    log_warn "(Secret/${J2026_GATEWAY_IAP_SECRET} has an empty client_id)."
    log_warn "IAP is enabled with an empty OAuth client, so this backend's"
    log_warn "public URL will return errors until IAP_OAUTH_CLIENT_ID/"
    log_warn "IAP_OAUTH_CLIENT_SECRET are set - see README.md \"Public access"
    log_warn "(GKE Gateway API + IAP)\"."
  fi
done

cat >"${GENERATED_DIR}/gcpbackendpolicy-jenkins.yaml" <<EOF
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_JENKINS}
  namespace: ${J2026_JENKINS_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_JENKINS_RELEASE}
  default:
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_JENKINS_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOF

cat >"${GENERATED_DIR}/gcpbackendpolicy-headlamp.yaml" <<EOF
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_HEADLAMP}
  namespace: ${J2026_HEADLAMP_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_HEADLAMP_RELEASE}
  default:
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_HEADLAMP_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOF

log_step "Applying Gateway resources"
kubectl apply -f "${GENERATED_DIR}/"

log_info "Gateway ready (certificate provisioning can take up to ~1h after DNS is set up)."
log_info "  Jenkins:   https://${J2026_GATEWAY_JENKINS_HOST}"
log_info "  PetClinic: https://${J2026_GATEWAY_PETCLINIC_HOST}"
log_info "  Headlamp:  https://${J2026_GATEWAY_HEADLAMP_HOST}"
