#!/usr/bin/env bash
# Exposes Jenkins, ArgoCD, Microservices and Headlamp on the public internet via the GKE
# Gateway API: one global external HTTPS Gateway (gke-l7-global-external-managed,
# using the static IP + managed certificate from terraform/gateway-bootstrap),
# one HTTPRoute per app, and a GCPBackendPolicy enabling Identity-Aware Proxy
# (IAP) in front of the Jenkins and Headlamp Services only - Microservices stays
# public. See README.md "Public access (GKE Gateway API + IAP)".
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
source "$(dirname "${BASH_SOURCE[0]}")/lib/config.sh"

if [[ -z "${J2026_GATEWAY_BASE_DOMAIN}" ]]; then
  log_info "gateway.baseDomain / JENKINS2026_BASE_DOMAIN is empty - gateway disabled, skipping."
  log_info "(set it, after running the Day0.infra.01-gateway bootstrap workflow once, to enable public access)"
  exit 0
fi

if [[ "${J2026_PLATFORM}" != "gke" ]]; then
  log_info "platform.target='${J2026_PLATFORM}' - the gke-l7-global-external-managed"
  log_info "GatewayClass and GCPBackendPolicy are GKE-specific, skipping."
  exit 0
fi

GENERATED_DIR="${J2026_ROOT_DIR}/.generated/gateway"
mkdir -p "${GENERATED_DIR}"

# Fixed names
J2026_GATEWAY_HOST_ARGOCD="argocd"
export J2026_GATEWAY_ARGOCD_HOST="${J2026_GATEWAY_HOST_ARGOCD}.${J2026_GATEWAY_BASE_DOMAIN}"

log_step "Generating Gateway (static IP '${J2026_GATEWAY_STATIC_IP_NAME}', certmap '${J2026_GATEWAY_CERTMAP_NAME}')"
cat >"${GENERATED_DIR}/gateway.yaml" <<EOT
# Generated by scripts/09-gateway.sh from config/config.yaml - do not edit by
# hand, do not commit (see .gitignore).
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${J2026_GATEWAY_NAME}
  namespace: ${J2026_GATEWAY_NAMESPACE}
  annotations:
    networking.gke.io/certmap: ${J2026_GATEWAY_CERTMAP_NAME}
spec:
  gatewayClassName: gke-l7-global-external-managed
  addresses:
    - type: NamedAddress
      value: ${J2026_GATEWAY_STATIC_IP_NAME}
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        options:
          networking.gke.io/pre-shared-certs: ""
      allowedRoutes:
        namespaces:
          from: All
EOT

log_step "Generating HTTPRoutes (argocd, microservices, headlamp; jenkins only when ci.engine=jenkins)"
# Jenkins HTTPRoute only when Jenkins is the CI engine - in tekton mode there is
# no Jenkins Service to route to (04-tekton.sh retires it).
if [[ "${J2026_CI_ENGINE}" != "tekton" ]]; then
  cat >"${GENERATED_DIR}/httproute-jenkins.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_JENKINS}
  namespace: ${J2026_JENKINS_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_JENKINS_HOST}"
  rules:
    - backendRefs:
        - name: ${J2026_JENKINS_RELEASE}
          port: 8080
EOT
fi

cat >"${GENERATED_DIR}/httproute-argocd.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_ARGOCD_HOST}"
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
EOT

cat >"${GENERATED_DIR}/httproute-microservices.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_MICROSERVICES}
  namespace: ${J2026_MICROSERVICES_NS_STABLE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_MICROSERVICES_HOST}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gateway
          port: 8080
EOT

# Optional lean develop tier - only routed when microservices.developTrackEnabled
# (the namespace itself is created by 01-namespaces.sh under the same flag). Public,
# NO IAP - same edge posture as the stable microservices host. Mirrors the grafana
# enable/cleanup pattern below so disabling the tier on a persistent cluster retires
# its dangling route/policy instead of leaving a 502 at the develop host.
if [[ "${J2026_MICROSERVICES_DEVELOP_TRACK_ENABLED}" == "true" ]]; then
  log_step "Generating HTTPRoute + HealthCheckPolicy (microservices develop tier)"
  cat >"${GENERATED_DIR}/httproute-microservices-develop.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_MICROSERVICES_DEVELOP}
  namespace: ${J2026_MICROSERVICES_DEVELOP_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_MICROSERVICES_DEVELOP_HOST}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gateway
          port: 8080
EOT

  cat >"${GENERATED_DIR}/healthcheckpolicy-microservices-develop.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: gateway
  namespace: ${J2026_MICROSERVICES_DEVELOP_NAMESPACE}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /management/health
  targetRef:
    group: ""
    kind: Service
    name: gateway
EOT
else
  # Develop tier disabled - retire any route/policy left over from a previous
  # develop_track run on this (persistent) cluster, but only when the namespace
  # still exists (--ignore-not-found doesn't cover a missing namespace). Also drop
  # any stale generated manifests so the apply below can't re-create the route.
  rm -f "${GENERATED_DIR}/httproute-microservices-develop.yaml" \
        "${GENERATED_DIR}/healthcheckpolicy-microservices-develop.yaml"
  if kubectl get namespace "${J2026_MICROSERVICES_DEVELOP_NAMESPACE}" >/dev/null 2>&1; then
    log_step "Removing any leftover microservices-develop HTTPRoute/HealthCheckPolicy (developTrackEnabled=false)"
    kubectl delete httproute "${J2026_GATEWAY_HTTPROUTE_MICROSERVICES_DEVELOP}" -n "${J2026_MICROSERVICES_DEVELOP_NAMESPACE}" --ignore-not-found
    kubectl delete healthcheckpolicy gateway -n "${J2026_MICROSERVICES_DEVELOP_NAMESPACE}" --ignore-not-found
  fi
fi

cat >"${GENERATED_DIR}/httproute-headlamp.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_HEADLAMP}
  namespace: ${J2026_HEADLAMP_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_HEADLAMP_HOST}"
  rules:
    - backendRefs:
        - name: ${J2026_HEADLAMP_RELEASE}
          port: 80
EOT

cat >"${GENERATED_DIR}/httproute-pgadmin.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_PGADMIN}
  namespace: ${J2026_PGADMIN_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_PGADMIN_HOST}"
  rules:
    - backendRefs:
        - name: ${J2026_PGADMIN_RELEASE}-pgadmin4
          port: 80
EOT

# Tekton Dashboard is only deployed when ci.engine=tekton.
if [[ "${J2026_CI_ENGINE}" == "tekton" ]]; then
  log_step "Generating HTTPRoute + HealthCheckPolicy (tekton dashboard, ci.engine=tekton)"
  cat >"${GENERATED_DIR}/httproute-tekton.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_TEKTON}
  namespace: ${J2026_TEKTON_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_TEKTON_HOST}"
  rules:
    - backendRefs:
        - name: ${J2026_TEKTON_DASHBOARD_SERVICE}
          port: ${J2026_TEKTON_DASHBOARD_PORT}
EOT

  cat >"${GENERATED_DIR}/healthcheckpolicy-tekton.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ${J2026_TEKTON_DASHBOARD_SERVICE}
  namespace: ${J2026_TEKTON_NAMESPACE}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_TEKTON_DASHBOARD_SERVICE}
EOT

  # Pipelines-as-Code controller (webhook receiver) - public, NO IAP (GitHub must
  # reach it; the webhook HMAC secret authenticates requests).
  cat >"${GENERATED_DIR}/httproute-pac.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_PAC}
  namespace: pipelines-as-code
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_PAC_HOST}"
  rules:
    - backendRefs:
        - name: pipelines-as-code-controller
          port: 8080
EOT
fi

# Grafana is only deployed in-cluster (and thus exposable) in
# observability.mode=oss. In grafana-cloud mode it lives at *.grafana.net, so
# there's no in-cluster Service to route to.
if [[ "${J2026_OBS_MODE}" == "oss" ]]; then
  log_step "Generating HTTPRoute (grafana, observability.mode=oss)"
  cat >"${GENERATED_DIR}/httproute-grafana.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_GRAFANA}
  namespace: ${J2026_GRAFANA_OSS_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_GRAFANA_HOST}"
  rules:
    - backendRefs:
        - name: oss-kube-prometheus-stack-grafana
          port: 80
EOT

  cat >"${GENERATED_DIR}/healthcheckpolicy-grafana.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: oss-kube-prometheus-stack-grafana
  namespace: ${J2026_GRAFANA_OSS_NAMESPACE}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /api/health
  targetRef:
    group: ""
    kind: Service
    name: oss-kube-prometheus-stack-grafana
EOT
else
  # Non-oss modes have no in-cluster Grafana. Delete any grafana HTTPRoute /
  # HealthCheckPolicy left over from a previous oss run on this (persistent) cluster
  # — otherwise it dangles pointing at the now-deleted oss-kube-prometheus-stack-grafana
  # Service (BackendNotFound events + a 502 at the grafana host). Deterministic
  # mode-switch cleanup, mirroring 03-observability retiring foreign backends. Idempotent.
  log_step "Removing any leftover grafana HTTPRoute/HealthCheckPolicy (observability.mode=${J2026_OBS_MODE}, not oss)"
  kubectl delete httproute "${J2026_GATEWAY_HTTPROUTE_GRAFANA}" -n "${J2026_GRAFANA_OSS_NAMESPACE}" --ignore-not-found
  kubectl delete healthcheckpolicy oss-kube-prometheus-stack-grafana -n "${J2026_GRAFANA_OSS_NAMESPACE}" --ignore-not-found
fi


log_step "Generating HealthCheckPolicies (argocd, microservices; jenkins only when ci.engine=jenkins)"
if [[ "${J2026_CI_ENGINE}" != "tekton" ]]; then
  cat >"${GENERATED_DIR}/healthcheckpolicy-jenkins.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ${J2026_JENKINS_RELEASE}
  namespace: ${J2026_JENKINS_NAMESPACE}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /login
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_JENKINS_RELEASE}
EOT
fi

cat >"${GENERATED_DIR}/healthcheckpolicy-argocd.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: argocd-server
  namespace: argocd
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
EOT

cat >"${GENERATED_DIR}/healthcheckpolicy-microservices.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: gateway
  namespace: ${J2026_MICROSERVICES_NS_STABLE}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /management/health
  targetRef:
    group: ""
    kind: Service
    name: gateway
EOT

log_step "Generating GCPBackendPolicies (IAP for jenkins, headlamp, pgadmin)"
declare -A iap_client_id
# The OSS Grafana (observability.mode=oss) is IAP-protected too - same edge
# pattern as Jenkins/Headlamp. Its namespace only needs the per-namespace
# client secret in that mode.
iap_backend_namespaces=("${J2026_HEADLAMP_NAMESPACE}" "${J2026_PGADMIN_NAMESPACE}")
# Jenkins is an IAP backend only when it is the CI engine (no Jenkins Service in
# tekton mode); the Tekton Dashboard is the IAP backend instead when ci.engine=tekton.
if [[ "${J2026_CI_ENGINE}" == "tekton" ]]; then
  iap_backend_namespaces+=("${J2026_TEKTON_NAMESPACE}")
else
  iap_backend_namespaces+=("${J2026_JENKINS_NAMESPACE}")
fi
if [[ "${J2026_OBS_MODE}" == "oss" ]]; then
  iap_backend_namespaces+=("${J2026_GRAFANA_OSS_NAMESPACE}")
fi
for ns in "${iap_backend_namespaces[@]}"; do
  client_id="$(kubectl get secret "${J2026_GATEWAY_IAP_SECRET}" -n "${ns}" -o jsonpath='{.data.client_id}' 2>/dev/null | base64 -d || true)"
  client_secret="$(kubectl get secret "${J2026_GATEWAY_IAP_SECRET}" -n "${ns}" -o jsonpath='{.data.client_secret}' 2>/dev/null | base64 -d || true)"
  iap_client_id["${ns}"]="${client_id}"
  if [[ "$(j2026_active_secrets_backend)" != "eso" ]]; then
    # eso → the ${IAP}-client-secret ExternalSecret (08.6) projects client_secret
    # straight from Secret Manager; skip the imperative re-projection here.
    kubectl create secret generic "${J2026_GATEWAY_IAP_SECRET}-client-secret" -n "${ns}" \
      --from-literal=client_secret="${client_secret}" \
      --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  fi

  if [[ -z "${client_id}" ]]; then
    log_warn "IAP OAuth credentials are not configured in namespace '${ns}'"
  fi
done

if [[ "${J2026_CI_ENGINE}" != "tekton" ]]; then
  cat >"${GENERATED_DIR}/gcpbackendpolicy-jenkins.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_JENKINS}
  namespace: ${J2026_JENKINS_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_JENKINS_RELEASE}
  default:
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_JENKINS_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOT
fi

cat >"${GENERATED_DIR}/gcpbackendpolicy-headlamp.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_HEADLAMP}
  namespace: ${J2026_HEADLAMP_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_HEADLAMP_RELEASE}
  default:
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_HEADLAMP_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOT

cat >"${GENERATED_DIR}/gcpbackendpolicy-pgadmin.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_PGADMIN}
  namespace: ${J2026_PGADMIN_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_PGADMIN_RELEASE}-pgadmin4
  default:
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_PGADMIN_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOT

if [[ "${J2026_CI_ENGINE}" == "tekton" ]]; then
  cat >"${GENERATED_DIR}/gcpbackendpolicy-tekton.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_TEKTON}
  namespace: ${J2026_TEKTON_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_TEKTON_DASHBOARD_SERVICE}
  default:
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_TEKTON_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOT
fi

if [[ "${J2026_OBS_MODE}" == "oss" ]]; then
  cat >"${GENERATED_DIR}/gcpbackendpolicy-grafana.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_GRAFANA}
  namespace: ${J2026_GRAFANA_OSS_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: oss-kube-prometheus-stack-grafana
  default:
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_GRAFANA_OSS_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOT
fi


log_step "Applying Gateway resources"
kubectl apply -f "${GENERATED_DIR}/"

log_info "Gateway ready."
if [[ "${J2026_CI_ENGINE}" != "tekton" ]]; then
  log_info "  Jenkins:           https://${J2026_GATEWAY_JENKINS_HOST}"
fi
log_info "  ArgoCD:            https://${J2026_GATEWAY_ARGOCD_HOST}"
log_info "  Microservices:         https://${J2026_GATEWAY_MICROSERVICES_HOST}"
if [[ "${J2026_MICROSERVICES_DEVELOP_TRACK_ENABLED}" == "true" ]]; then
  log_info "  Microservices develop: https://${J2026_GATEWAY_MICROSERVICES_DEVELOP_HOST}"
fi
log_info "  Headlamp:          https://${J2026_GATEWAY_HEADLAMP_HOST}"
log_info "  pgAdmin:           https://${J2026_GATEWAY_PGADMIN_HOST}"
if [[ "${J2026_CI_ENGINE}" == "tekton" ]]; then
  log_info "  Tekton Dashboard:  https://${J2026_GATEWAY_TEKTON_HOST} (IAP-protected)"
fi
if [[ "${J2026_OBS_MODE}" == "oss" ]]; then
  log_info "  Grafana:           https://${J2026_GATEWAY_GRAFANA_HOST} (IAP-protected)"
fi
