#!/usr/bin/env bash
# Exposes Jenkins, ArgoCD, Microservices and Headlamp on the public internet via the GKE
# Gateway API: one global external HTTPS Gateway (gke-l7-global-external-managed,
# using the static IP + managed certificate from terraform/gateway-bootstrap),
# one HTTPRoute per app, and a GCPBackendPolicy enabling Identity-Aware Proxy
# (IAP) in front of the Jenkins and Headlamp Services only - Microservices stays
# public. See README.md "Public access (GKE Gateway API + IAP)".
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
source "$(dirname "${BASH_SOURCE[0]}")/lib/config.sh"

if [[ -z "${J2026_GATEWAY_BASE_DOMAIN}" ]]; then
  log_info "gateway.baseDomain / JENKINS2026_BASE_DOMAIN is empty - gateway disabled, skipping."
  log_info "(set it, after running the Day0.infra.01-gateway bootstrap workflow once, to enable public access)"
  exit 0
fi

if [[ "${J2026_PLATFORM}" != "gke" ]]; then
  log_info "platform.target='${J2026_PLATFORM}' - the gke-l7-global-external-managed"
  log_info "GatewayClass and GCPBackendPolicy are GKE-specific, skipping."
  exit 0
fi

GENERATED_DIR="${J2026_ROOT_DIR}/.generated/gateway"
mkdir -p "${GENERATED_DIR}"

# Backend TLS (LB→pod re-encryption, docs/504) - resolved ONCE: flag AND the
# BackendTLSPolicy CRD (j2026_backend_tls_active, lib/common.sh). Drives the
# per-TLS-ready-backend BackendTLSPolicy + HTTPS HealthCheckPolicy blocks below.
BACKEND_TLS_ACTIVE="$(j2026_backend_tls_active)"
# argocd-server has a SECOND gate: its deploy caller must speak TLS (jenkins/
# githubactions only). Drives the argocd BackendTLSPolicy + HTTPS-vs-HTTP health
# check below, so tekton/argo clusters keep a plaintext argocd + HTTP probe.
ARGOCD_TLS_ACTIVE="$(j2026_argocd_backend_tls_active)"

# Fixed names
J2026_GATEWAY_HOST_ARGOCD="argocd"
export J2026_GATEWAY_ARGOCD_HOST="${J2026_GATEWAY_HOST_ARGOCD}.${J2026_GATEWAY_BASE_DOMAIN}"

log_step "Generating Gateway (static IP '${J2026_GATEWAY_STATIC_IP_NAME}', certmap '${J2026_GATEWAY_CERTMAP_NAME}')"
cat >"${GENERATED_DIR}/gateway.yaml" <<EOT
# Generated by scripts/09-gateway.sh from config/config.yaml - do not edit by
# hand, do not commit (see .gitignore).
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${J2026_GATEWAY_NAME}
  namespace: ${J2026_GATEWAY_NAMESPACE}
  annotations:
    networking.gke.io/certmap: ${J2026_GATEWAY_CERTMAP_NAME}
spec:
  gatewayClassName: gke-l7-global-external-managed
  addresses:
    - type: NamedAddress
      value: ${J2026_GATEWAY_STATIC_IP_NAME}
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        options:
          networking.gke.io/pre-shared-certs: ""
      allowedRoutes:
        namespaces:
          from: All
EOT

log_step "Generating HTTPRoutes (argocd, microservices, headlamp; jenkins only when ci.engine=jenkins)"
# Jenkins HTTPRoute only when Jenkins is the CI engine - the other engines retire
# the Jenkins Service (tekton/githubactions/argoworkflows), so route to it ONLY for
# ci.engine=jenkins (an explicit == check, not != tekton, so githubactions and
# argoworkflows - which also have no Jenkins Service - emit no jenkins route).
if [[ "${J2026_CI_ENGINE}" == "jenkins" ]]; then
  cat >"${GENERATED_DIR}/httproute-jenkins.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_JENKINS}
  namespace: ${J2026_JENKINS_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_JENKINS_HOST}"
  rules:
    - backendRefs:
        - name: ${J2026_JENKINS_RELEASE}
          port: 8080
EOT
fi

cat >"${GENERATED_DIR}/httproute-argocd.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_ARGOCD_HOST}"
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
EOT

cat >"${GENERATED_DIR}/httproute-microservices.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_MICROSERVICES}
  namespace: ${J2026_MICROSERVICES_NS_STABLE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_MICROSERVICES_HOST}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gateway
          port: 8080
EOT

# Grafana Faro RUM beacon endpoint (browser → otel-collector faro receiver :8027).
# Public, NO IAP (browser-facing; the receiver is CORS-open). The LB health check is
# TCP on 8027 — the faro receiver only answers POST, so an HTTP GET probe would mark
# the backend unhealthy → 502. The wildcard cert + *.<baseDomain> DNS already cover
# this host, so no per-host DNS is needed. Used by the Angular SPA's Faro Web SDK.
cat >"${GENERATED_DIR}/httproute-faro.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_FARO}
  namespace: ${J2026_OBS_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_FARO_HOST}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: otel-collector-gateway
          port: 8027
EOT

cat >"${GENERATED_DIR}/healthcheckpolicy-faro.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_FARO}
  namespace: ${J2026_OBS_NAMESPACE}
spec:
  default:
    config:
      type: TCP
      tcpHealthCheck:
        port: 8027
  targetRef:
    group: ""
    kind: Service
    name: otel-collector-gateway
EOT

# Backend TLS for the faro (RUM) receiver (stage-2 TLS-ready backend; opt-in via
# gateway.backendTls.enabled - docs/504). When active, the otel-collector faro
# receiver serves TLS on 8027 (values-backend-tls.yaml overlay added by
# 03-observability.sh; cert + CA trust ConfigMap minted by 08.7-backend-tls.sh).
# Only the BackendTLSPolicy flips here - the faro HealthCheckPolicy above stays
# TCP (protocol-agnostic, so it survives the plain->TLS switch, unlike headlamp's
# HTTP probe which had to become HTTPS). The HTTPRoute is unchanged (still targets
# Service port 8027). Same j2026_backend_tls_active gate as the collector overlay.
if [[ "${BACKEND_TLS_ACTIVE}" == "true" ]]; then
  log_step "Generating BackendTLSPolicy (faro receiver, backendTls enabled)"
  cat >"${GENERATED_DIR}/backendtlspolicy-faro.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: ${J2026_BACKEND_TLS_POLICY_FARO}
  namespace: ${J2026_OBS_NAMESPACE}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: otel-collector-gateway
  validation:
    hostname: otel-collector-gateway.${J2026_OBS_NAMESPACE}.svc.cluster.local
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: ${J2026_BACKEND_TLS_CA_CONFIGMAP}
EOT
else
  # Inactive - retire any faro BackendTLSPolicy from a previous enabled run and
  # drop the stale manifest so the directory-apply can't re-create it (CRD-guarded
  # delete, same as the headlamp block).
  rm -f "${GENERATED_DIR}/backendtlspolicy-faro.yaml"
  if kubectl get namespace "${J2026_OBS_NAMESPACE}" >/dev/null 2>&1 \
     && kubectl get crd backendtlspolicies.gateway.networking.k8s.io >/dev/null 2>&1; then
    log_step "Removing any leftover faro BackendTLSPolicy (backendTls inactive)"
    kubectl delete backendtlspolicy "${J2026_BACKEND_TLS_POLICY_FARO}" -n "${J2026_OBS_NAMESPACE}" --ignore-not-found
  fi
fi

# Optional lean develop tier - only routed when microservices.developTrackEnabled
# (the namespace itself is created by 01-namespaces.sh under the same flag). Public,
# NO IAP - same edge posture as the stable microservices host. Mirrors the grafana
# enable/cleanup pattern below so disabling the tier on a persistent cluster retires
# its dangling route/policy instead of leaving a 502 at the develop host.
if [[ "${J2026_MICROSERVICES_DEVELOP_TRACK_ENABLED}" == "true" ]]; then
  log_step "Generating HTTPRoute + HealthCheckPolicy (microservices develop tier)"
  cat >"${GENERATED_DIR}/httproute-microservices-develop.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_MICROSERVICES_DEVELOP}
  namespace: ${J2026_MICROSERVICES_DEVELOP_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_MICROSERVICES_DEVELOP_HOST}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gateway
          port: 8080
EOT

  cat >"${GENERATED_DIR}/healthcheckpolicy-microservices-develop.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: gateway
  namespace: ${J2026_MICROSERVICES_DEVELOP_NAMESPACE}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /management/health
  targetRef:
    group: ""
    kind: Service
    name: gateway
EOT
else
  # Develop tier disabled - retire any route/policy left over from a previous
  # develop_track run on this (persistent) cluster, but only when the namespace
  # still exists (--ignore-not-found doesn't cover a missing namespace). Also drop
  # any stale generated manifests so the apply below can't re-create the route.
  rm -f "${GENERATED_DIR}/httproute-microservices-develop.yaml" \
        "${GENERATED_DIR}/healthcheckpolicy-microservices-develop.yaml"
  if kubectl get namespace "${J2026_MICROSERVICES_DEVELOP_NAMESPACE}" >/dev/null 2>&1; then
    log_step "Removing any leftover microservices-develop HTTPRoute/HealthCheckPolicy (developTrackEnabled=false)"
    kubectl delete httproute "${J2026_GATEWAY_HTTPROUTE_MICROSERVICES_DEVELOP}" -n "${J2026_MICROSERVICES_DEVELOP_NAMESPACE}" --ignore-not-found
    kubectl delete healthcheckpolicy gateway -n "${J2026_MICROSERVICES_DEVELOP_NAMESPACE}" --ignore-not-found
  fi
fi

cat >"${GENERATED_DIR}/httproute-headlamp.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_HEADLAMP}
  namespace: ${J2026_HEADLAMP_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_HEADLAMP_HOST}"
  rules:
    - backendRefs:
        - name: ${J2026_HEADLAMP_RELEASE}
          port: 80
EOT

# Backend TLS for Headlamp (stage-1 TLS-ready backend; opt-in via
# gateway.backendTls.enabled - docs/504). When active, headlamp-server itself
# terminates TLS on its pod port 4466 (values-backend-tls.yaml overlay added by
# 08.5-argocd.sh; cert + CA trust ConfigMap minted by 08.7-backend-tls.sh), and
# two policies flip the LB side:
#   - BackendTLSPolicy: the LB re-encrypts LB→pod AND validates the backend
#     cert against the internal CA (caCertificateRefs -> ConfigMap key ca.crt,
#     same namespace). validation.hostname is BOTH the SNI sent and the SAN
#     validated, so it must match the cert 08.7 mints (the Service FQDN).
#   - HealthCheckPolicy type HTTPS: the default LB health check follows the
#     Service appProtocol (unset here = HTTP) - it would keep probing plain
#     HTTP against the now-TLS pod, mark the backend unhealthy, and the host
#     would 502 (same failure family as the faro/argo-events GET-vs-POST
#     probes above). No port override: it probes the serving (pod) port.
# The HTTPRoute and the IAP GCPBackendPolicy are UNCHANGED - the route still
# targets Service port 80 (targetPort 4466), and IAP composes with backend TLS.
if [[ "${BACKEND_TLS_ACTIVE}" == "true" ]]; then
  log_step "Generating BackendTLSPolicy + HTTPS HealthCheckPolicy (headlamp, backendTls enabled)"
  cat >"${GENERATED_DIR}/backendtlspolicy-headlamp.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: ${J2026_BACKEND_TLS_POLICY_HEADLAMP}
  namespace: ${J2026_HEADLAMP_NAMESPACE}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: ${J2026_HEADLAMP_RELEASE}
  validation:
    hostname: ${J2026_HEADLAMP_RELEASE}.${J2026_HEADLAMP_NAMESPACE}.svc.cluster.local
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: ${J2026_BACKEND_TLS_CA_CONFIGMAP}
EOT

  cat >"${GENERATED_DIR}/healthcheckpolicy-headlamp.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ${J2026_HEADLAMP_RELEASE}
  namespace: ${J2026_HEADLAMP_NAMESPACE}
spec:
  default:
    config:
      type: HTTPS
      httpsHealthCheck:
        requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_HEADLAMP_RELEASE}
EOT
else
  # Backend TLS inactive - retire any policies left by a previous enabled run
  # on this (persistent) cluster, and drop stale generated manifests so the
  # apply below can't re-create them (same deterministic flag-off cleanup as
  # the develop-tier/grafana blocks). The CRD guard matters: `kubectl delete
  # backendtlspolicy` on a cluster that never served the CRD is a hard error,
  # not a not-found.
  rm -f "${GENERATED_DIR}/backendtlspolicy-headlamp.yaml" \
        "${GENERATED_DIR}/healthcheckpolicy-headlamp.yaml"
  if kubectl get namespace "${J2026_HEADLAMP_NAMESPACE}" >/dev/null 2>&1; then
    log_step "Removing any leftover headlamp BackendTLSPolicy/HealthCheckPolicy (backendTls inactive)"
    if kubectl get crd backendtlspolicies.gateway.networking.k8s.io >/dev/null 2>&1; then
      kubectl delete backendtlspolicy "${J2026_BACKEND_TLS_POLICY_HEADLAMP}" -n "${J2026_HEADLAMP_NAMESPACE}" --ignore-not-found
    fi
    kubectl delete healthcheckpolicy "${J2026_HEADLAMP_RELEASE}" -n "${J2026_HEADLAMP_NAMESPACE}" --ignore-not-found
  fi
fi

cat >"${GENERATED_DIR}/httproute-pgadmin.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_PGADMIN}
  namespace: ${J2026_PGADMIN_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_PGADMIN_HOST}"
  rules:
    - backendRefs:
        - name: ${J2026_PGADMIN_RELEASE}-pgadmin4
          port: 80
EOT

# Tekton Dashboard is only deployed when ci.engine=tekton.
if [[ "${J2026_CI_ENGINE}" == "tekton" ]]; then
  log_step "Generating HTTPRoute + HealthCheckPolicy (tekton dashboard, ci.engine=tekton)"
  cat >"${GENERATED_DIR}/httproute-tekton.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_TEKTON}
  namespace: ${J2026_TEKTON_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_TEKTON_HOST}"
  rules:
    - backendRefs:
        - name: ${J2026_TEKTON_DASHBOARD_SERVICE}
          port: ${J2026_TEKTON_DASHBOARD_PORT}
EOT

  cat >"${GENERATED_DIR}/healthcheckpolicy-tekton.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ${J2026_TEKTON_DASHBOARD_SERVICE}
  namespace: ${J2026_TEKTON_NAMESPACE}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_TEKTON_DASHBOARD_SERVICE}
EOT

  # Pipelines-as-Code controller (webhook receiver) - public, NO IAP (GitHub must
  # reach it; the webhook HMAC secret authenticates requests).
  cat >"${GENERATED_DIR}/httproute-pac.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_PAC}
  namespace: pipelines-as-code
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_PAC_HOST}"
  rules:
    - backendRefs:
        - name: pipelines-as-code-controller
          port: 8080
EOT
fi

# Argo Workflows Server UI is only deployed when ci.engine=argoworkflows. The Server runs
# with --auth-mode=server --secure=false (plain HTTP), so it is IAP-protected at the
# Gateway (GCPBackendPolicy below), exactly like the no-native-auth Tekton Dashboard.
if [[ "${J2026_CI_ENGINE}" == "argoworkflows" ]]; then
  log_step "Generating HTTPRoute + HealthCheckPolicy (Argo Workflows Server, ci.engine=argoworkflows)"
  cat >"${GENERATED_DIR}/httproute-argoworkflows.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_ARGOWF}
  namespace: ${J2026_ARGOWF_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_ARGOWF_HOST}"
  rules:
    - backendRefs:
        - name: ${J2026_ARGOWF_SERVER_SERVICE}
          port: ${J2026_ARGOWF_SERVER_PORT}
EOT

  cat >"${GENERATED_DIR}/healthcheckpolicy-argoworkflows.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ${J2026_ARGOWF_SERVER_SERVICE}
  namespace: ${J2026_ARGOWF_NAMESPACE}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_ARGOWF_SERVER_SERVICE}
EOT

  # Argo Events EventSource (webhook receiver) - public, NO IAP (GitHub must reach it;
  # the argoworkflows-github-webhook HMAC secret authenticates requests). The github
  # EventSource provisions the Service github-eventsource-svc on port 12000.
  cat >"${GENERATED_DIR}/httproute-argoevents.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_ARGOEVENTS}
  namespace: ${J2026_ARGOWF_EVENTS_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_ARGOEVENTS_HOST}"
  rules:
    - backendRefs:
        - name: github-eventsource-svc
          port: 12000
EOT

  # The github EventSource only answers POST at /push, so the default HTTP-GET-/ health
  # probe marks the backend unhealthy and the public endpoint 503s (the same failure mode
  # as the faro receiver above). Use a TCP health check on 12000 so health == "port open".
  cat >"${GENERATED_DIR}/healthcheckpolicy-argoevents.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_ARGOEVENTS}
  namespace: ${J2026_ARGOWF_EVENTS_NAMESPACE}
spec:
  default:
    config:
      type: TCP
      tcpHealthCheck:
        port: 12000
  targetRef:
    group: ""
    kind: Service
    name: github-eventsource-svc
EOT
fi

# Grafana is only deployed in-cluster (and thus exposable) in
# observability.mode=oss. In grafana-cloud mode it lives at *.grafana.net, so
# there's no in-cluster Service to route to.
if [[ "${J2026_OBS_MODE}" == "oss" ]]; then
  log_step "Generating HTTPRoute (grafana, observability.mode=oss)"
  cat >"${GENERATED_DIR}/httproute-grafana.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${J2026_GATEWAY_HTTPROUTE_GRAFANA}
  namespace: ${J2026_GRAFANA_OSS_NAMESPACE}
spec:
  parentRefs:
    - name: ${J2026_GATEWAY_NAME}
      namespace: ${J2026_GATEWAY_NAMESPACE}
      sectionName: https
  hostnames:
    - "${J2026_GATEWAY_GRAFANA_HOST}"
  rules:
    - backendRefs:
        - name: oss-kube-prometheus-stack-grafana
          port: 80
EOT

  cat >"${GENERATED_DIR}/healthcheckpolicy-grafana.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: oss-kube-prometheus-stack-grafana
  namespace: ${J2026_GRAFANA_OSS_NAMESPACE}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /api/health
  targetRef:
    group: ""
    kind: Service
    name: oss-kube-prometheus-stack-grafana
EOT
else
  # Non-oss modes have no in-cluster Grafana. Delete any grafana HTTPRoute /
  # HealthCheckPolicy left over from a previous oss run on this (persistent) cluster
  # — otherwise it dangles pointing at the now-deleted oss-kube-prometheus-stack-grafana
  # Service (BackendNotFound events + a 502 at the grafana host). Deterministic
  # mode-switch cleanup, mirroring 03-observability retiring foreign backends. Idempotent.
  log_step "Removing any leftover grafana HTTPRoute/HealthCheckPolicy (observability.mode=${J2026_OBS_MODE}, not oss)"
  kubectl delete httproute "${J2026_GATEWAY_HTTPROUTE_GRAFANA}" -n "${J2026_GRAFANA_OSS_NAMESPACE}" --ignore-not-found
  kubectl delete healthcheckpolicy oss-kube-prometheus-stack-grafana -n "${J2026_GRAFANA_OSS_NAMESPACE}" --ignore-not-found
fi


log_step "Generating HealthCheckPolicies (argocd, microservices; jenkins only when ci.engine=jenkins)"
# Jenkins HealthCheckPolicy ONLY when Jenkins is the CI engine - the other engines retire
# the Jenkins Service + namespace (tekton/githubactions/argoworkflows), so an explicit ==
# check, not != tekton: != tekton wrongly emitted healthcheckpolicy-jenkins.yaml in
# githubactions/argoworkflows mode and `kubectl apply` failed with `namespaces "jenkins"
# not found` (the jenkins ns doesn't exist there).
if [[ "${J2026_CI_ENGINE}" == "jenkins" ]]; then
  cat >"${GENERATED_DIR}/healthcheckpolicy-jenkins.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ${J2026_JENKINS_RELEASE}
  namespace: ${J2026_JENKINS_NAMESPACE}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /login
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_JENKINS_RELEASE}
EOT
fi

# argocd health check: HTTPS once argocd-server serves TLS (ARGOCD_TLS_ACTIVE), else
# HTTP. The default probe follows the Service appProtocol (unset = HTTP); leaving it
# HTTP against a now-TLS argocd-server marks the backend unhealthy -> 502 on the UI.
if [[ "${ARGOCD_TLS_ACTIVE}" == "true" ]]; then
  argocd_hc_type="HTTPS"; argocd_hc_key="httpsHealthCheck"
else
  argocd_hc_type="HTTP"; argocd_hc_key="httpHealthCheck"
fi
cat >"${GENERATED_DIR}/healthcheckpolicy-argocd.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: argocd-server
  namespace: argocd
spec:
  default:
    config:
      type: ${argocd_hc_type}
      ${argocd_hc_key}:
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
EOT

# Backend TLS for argocd-server (stage-3; opt-in + engine-gated, docs/504). When
# ARGOCD_TLS_ACTIVE the LB re-encrypts + validates the ArgoCD UI hop against the
# internal CA (the health check above is already HTTPS). Retired (CRD-guarded) when
# off - covering BOTH flag-off and the engine-switch case (backend TLS on, but the
# tekton/argo caller can't do TLS), so a stale policy never 502s a plaintext argocd.
if [[ "${ARGOCD_TLS_ACTIVE}" == "true" ]]; then
  log_step "Generating BackendTLSPolicy (argocd-server, backendTls enabled)"
  cat >"${GENERATED_DIR}/backendtlspolicy-argocd.yaml" <<EOT
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: ${J2026_BACKEND_TLS_POLICY_ARGOCD}
  namespace: ${J2026_ARGOCD_NAMESPACE}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: argocd-server
  validation:
    hostname: argocd-server.${J2026_ARGOCD_NAMESPACE}.svc.cluster.local
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: ${J2026_BACKEND_TLS_CA_CONFIGMAP}
EOT
else
  rm -f "${GENERATED_DIR}/backendtlspolicy-argocd.yaml"
  if kubectl get namespace "${J2026_ARGOCD_NAMESPACE}" >/dev/null 2>&1 \
     && kubectl get crd backendtlspolicies.gateway.networking.k8s.io >/dev/null 2>&1; then
    log_step "Removing any leftover argocd BackendTLSPolicy (backendTls inactive or engine-gated off)"
    kubectl delete backendtlspolicy "${J2026_BACKEND_TLS_POLICY_ARGOCD}" -n "${J2026_ARGOCD_NAMESPACE}" --ignore-not-found
  fi
fi

cat >"${GENERATED_DIR}/healthcheckpolicy-microservices.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: gateway
  namespace: ${J2026_MICROSERVICES_NS_STABLE}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /management/health
  targetRef:
    group: ""
    kind: Service
    name: gateway
EOT

log_step "Generating GCPBackendPolicies (IAP for jenkins, argocd, headlamp, pgadmin)"
declare -A iap_client_id
# The OSS Grafana (observability.mode=oss) is IAP-protected too - same edge
# pattern as Jenkins/Headlamp. Its namespace only needs the per-namespace
# client secret in that mode.
iap_backend_namespaces=("${J2026_HEADLAMP_NAMESPACE}" "${J2026_PGADMIN_NAMESPACE}" "${J2026_ARGOCD_NAMESPACE}")
# Jenkins is an IAP backend only when it is the CI engine (no Jenkins Service in
# the other modes); the Tekton Dashboard is the IAP backend instead when
# ci.engine=tekton. ci.engine=githubactions has NO in-cluster CI dashboard (runs
# live in GitHub's Actions tab), so neither engine namespace is added - an explicit
# elif, not an else, so githubactions doesn't fall through to the jenkins branch.
if [[ "${J2026_CI_ENGINE}" == "tekton" ]]; then
  iap_backend_namespaces+=("${J2026_TEKTON_NAMESPACE}")
elif [[ "${J2026_CI_ENGINE}" == "jenkins" ]]; then
  iap_backend_namespaces+=("${J2026_JENKINS_NAMESPACE}")
elif [[ "${J2026_CI_ENGINE}" == "argoworkflows" ]]; then
  # The Argo Workflows Server UI is IAP-protected too (no native auth), like the Tekton
  # Dashboard. (githubactions has no in-cluster CI backend, so it adds none.)
  iap_backend_namespaces+=("${J2026_ARGOWF_NAMESPACE}")
fi
if [[ "${J2026_OBS_MODE}" == "oss" ]]; then
  iap_backend_namespaces+=("${J2026_GRAFANA_OSS_NAMESPACE}")
fi
for ns in "${iap_backend_namespaces[@]}"; do
  client_id="$(kubectl get secret "${J2026_GATEWAY_IAP_SECRET}" -n "${ns}" -o jsonpath='{.data.client_id}' 2>/dev/null | base64 -d || true)"
  client_secret="$(kubectl get secret "${J2026_GATEWAY_IAP_SECRET}" -n "${ns}" -o jsonpath='{.data.client_secret}' 2>/dev/null | base64 -d || true)"
  iap_client_id["${ns}"]="${client_id}"
  if [[ "$(j2026_active_secrets_backend)" != "eso" ]]; then
    # eso → the ${IAP}-client-secret ExternalSecret (08.6) projects client_secret
    # straight from Secret Manager; skip the imperative re-projection here.
    kubectl create secret generic "${J2026_GATEWAY_IAP_SECRET}-client-secret" -n "${ns}" \
      --from-literal=client_secret="${client_secret}" \
      --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  fi

  if [[ -z "${client_id}" ]]; then
    log_warn "IAP OAuth credentials are not configured in namespace '${ns}'"
  fi
done

if [[ "${J2026_CI_ENGINE}" == "jenkins" ]]; then
  cat >"${GENERATED_DIR}/gcpbackendpolicy-jenkins.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_JENKINS}
  namespace: ${J2026_JENKINS_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_JENKINS_RELEASE}
  default:
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_JENKINS_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOT
fi

cat >"${GENERATED_DIR}/gcpbackendpolicy-headlamp.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_HEADLAMP}
  namespace: ${J2026_HEADLAMP_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_HEADLAMP_RELEASE}
  default:
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_HEADLAMP_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOT

# ArgoCD IAP (defense-in-depth, docs/501): edge-block the argocd UI like the other
# admin UIs. ArgoCD's Dex authproxy connector (08.5-argocd.sh) trusts the IAP-injected
# X-Goog-Authenticated-User-Email header for single-sign-on + per-user RBAC. Composes
# with the argocd BackendTLSPolicy (both target the same Service, like headlamp). The
# header-spoof mitigation is the tightened argocd-baseline NetworkPolicy.
cat >"${GENERATED_DIR}/gcpbackendpolicy-argocd.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_ARGOCD}
  namespace: ${J2026_ARGOCD_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: argocd-server
  default:
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_ARGOCD_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOT

cat >"${GENERATED_DIR}/gcpbackendpolicy-pgadmin.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_PGADMIN}
  namespace: ${J2026_PGADMIN_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_PGADMIN_RELEASE}-pgadmin4
  default:
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_PGADMIN_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOT

if [[ "${J2026_CI_ENGINE}" == "tekton" ]]; then
  cat >"${GENERATED_DIR}/gcpbackendpolicy-tekton.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_TEKTON}
  namespace: ${J2026_TEKTON_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_TEKTON_DASHBOARD_SERVICE}
  default:
    # The Tekton Dashboard also serves long-lived watch/log streams behind IAP;
    # give it the same long backend timeout so streaming UI updates aren't cut by
    # the GKE ALB default 30s (same fix + rationale as the argoworkflows Server).
    timeoutSec: 3600
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_TEKTON_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOT
fi

if [[ "${J2026_CI_ENGINE}" == "argoworkflows" ]]; then
  cat >"${GENERATED_DIR}/gcpbackendpolicy-argoworkflows.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_ARGOWF}
  namespace: ${J2026_ARGOWF_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: ${J2026_ARGOWF_SERVER_SERVICE}
  default:
    # argo-server's /api/v1/workflow-events is a long-lived, server-streaming
    # (chunked) response that the Argo UI keeps open for live updates. The GKE
    # ALB default 30s backend-service response timeout severs it, so the UI
    # reconnects and re-dumps the full workflow list on a tight cadence ("Failed
    # to connect" toast). Verified the cut tracks timeoutSec exactly (set 120 →
    # streams cut at 120s); 1h keeps the watch effectively persistent and the UI
    # auto-reconnects. Per-Service policy, so this only affects the argo-server.
    timeoutSec: 3600
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_ARGOWF_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOT
fi

if [[ "${J2026_OBS_MODE}" == "oss" ]]; then
  cat >"${GENERATED_DIR}/gcpbackendpolicy-grafana.yaml" <<EOT
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: ${J2026_GATEWAY_IAP_POLICY_GRAFANA}
  namespace: ${J2026_GRAFANA_OSS_NAMESPACE}
spec:
  targetRef:
    group: ""
    kind: Service
    name: oss-kube-prometheus-stack-grafana
  default:
    iap:
      enabled: true
      clientID: "${iap_client_id[${J2026_GRAFANA_OSS_NAMESPACE}]}"
      oauth2ClientSecret:
        name: ${J2026_GATEWAY_IAP_SECRET}-client-secret
EOT
fi


log_step "Applying Gateway resources"
kubectl apply -f "${GENERATED_DIR}/"

# Backend TLS: the argocd-server HTTPS HealthCheckPolicy is now applied, so the
# NEG can finally go healthy (08.5 deliberately SKIPPED argocd-server's rollout
# wait - its readiness gate was blocked on this policy). Converge it here so the
# Day1 finishes with a Ready argocd. Non-fatal: a slow LB health-check reconcile
# shouldn't fail an otherwise-good run (the pod converges shortly after).
if [[ "${ARGOCD_TLS_ACTIVE}" == "true" ]]; then
  log_step "Waiting for argocd-server to become NEG-healthy under the new HTTPS health check"
  kubectl rollout status deployment argocd-server -n "${J2026_ARGOCD_NAMESPACE}" --timeout=6m || \
    log_warn "argocd-server rollout not confirmed within 6m - the LB HTTPS health-check reconcile may still be in flight; check 'kubectl -n ${J2026_ARGOCD_NAMESPACE} get pods' and the GCP backend health."
fi

log_info "Gateway ready."
if [[ "${J2026_CI_ENGINE}" == "jenkins" ]]; then
  log_info "  Jenkins:           https://${J2026_GATEWAY_JENKINS_HOST}"
fi
log_info "  ArgoCD:            https://${J2026_GATEWAY_ARGOCD_HOST}"
log_info "  Microservices:         https://${J2026_GATEWAY_MICROSERVICES_HOST}"
if [[ "${J2026_MICROSERVICES_DEVELOP_TRACK_ENABLED}" == "true" ]]; then
  log_info "  Microservices develop: https://${J2026_GATEWAY_MICROSERVICES_DEVELOP_HOST}"
fi
log_info "  Headlamp:          https://${J2026_GATEWAY_HEADLAMP_HOST}"
log_info "  pgAdmin:           https://${J2026_GATEWAY_PGADMIN_HOST}"
if [[ "${J2026_CI_ENGINE}" == "tekton" ]]; then
  log_info "  Tekton Dashboard:  https://${J2026_GATEWAY_TEKTON_HOST} (IAP-protected)"
fi
if [[ "${J2026_CI_ENGINE}" == "argoworkflows" ]]; then
  log_info "  Argo Workflows UI: https://${J2026_GATEWAY_ARGOWF_HOST} (IAP-protected)"
  log_info "  Argo Events hook:  https://${J2026_GATEWAY_ARGOEVENTS_HOST}/push (public, HMAC)"
fi
if [[ "${J2026_OBS_MODE}" == "oss" ]]; then
  log_info "  Grafana:           https://${J2026_GATEWAY_GRAFANA_HOST} (IAP-protected)"
fi
if [[ "${BACKEND_TLS_ACTIVE}" == "true" ]]; then
  log_info "  Backend TLS:       LB→pod re-encrypted + CA-validated for: headlamp (docs/504)"
fi
