apiVersion: karpenter.k8s.gcp/v1
kind: GCPNodeClass
metadata:
  name: ci-node-class
spec:
  # subnetSelector matches the subnets Karpenter can launch nodes into
  subnetSelector:
    karpenter.sh/discovery: jenkins-2026
  
  # imageFamily specifies the OS image type for the nodes (COS is optimized for container workloads)
  imageFamily: cos
  
  # disk config
  disks:
    - deviceName: boot
      type: pd-balanced
      sizeGb: 100
  
  # dynamic configuration mapping to GKE service accounts for Workload Identity
  serviceAccount: jenkins-2026-nodes@project.iam.gserviceaccount.com
  
  # metadata config
  metadata:
    disable-legacy-endpoints: "true"
  
  # network tags for firewall rule filtering
  tags:
    - jenkins-2026-karpenter
